name: Deploy Todo App

on:
  push:
    branches: [main]

jobs:
  deploy-backend:
    name: Deploy API to EC2
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2 and update
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/todo-ec2-app
            git pull
            cd todo-ec2-app
            npm install
            pm2 restart todo-app

  deploy-frontend:
    name: Deploy UI to S3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Build React app
        working-directory: todo-ec2-app/frontend
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: |
          npm ci
          npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload to S3
        run: aws s3 sync todo-ec2-app/frontend/dist/ s3://keval-todo-app-files-2026/ --delete